# Generated by Django 5.0.4 on 2024-04-25 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('articles', models.CharField(max_length=2000)),
                ('created_when', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
